### ISSUE TITLE
No send aprs data

### ISSUE THREAD

**Issue by lucamarche-iz1mlt** [g4klx/ircDDBGateway#3]
Hi everyone!!

I loaded the ircddbgateway version on raspberry pi but it seems to not send any message to the aprs server although it is perfectly connected and visible on the dashboard.
In the opendv version works, comparing the two codes there are some differences, maybe something may be missing?
Reading the code can not see a possible problem.

iz1mlt Luca

**Comment by lucamarche-iz1mlt** [comment]
I have add aprsPassoword. I also attach file of the configuration, think it's correct.
If my ircddgateway configuration is right will try to figure out if have done anything wrong.

[ircddbgateway.zip](https://github.com/g4klx/ircDDBGateway/files/2147109/ircddbgateway.zip)

iz1mlt Luca

**Comment by moiei** [comment]
I have been having the same issue for quite a time. I thought it was because of the lack of a password. Now, with the new aprsPassword=[aprs-is] the same issue keeps happening: very very few positions are reported.

I have checked the logs and I get a positive login:
```
M: 2018-07-02 21:28:00: Starting the APRS Writer thread
M: 2018-07-02 21:28:00: Received login banner : # aprsc 2.1.4-g408ed49
M: 2018-07-02 21:28:00: Response from APRS server: # logresp M0IEI-G verified, server T2FFL
M: 2018-07-02 21:28:00: Connected to the APRS server
```
But the position reports do not appear in aprs.fi

Could the position reports to the aprs server and the response be logged? Just to be sure whether the problems comes from the server or the ircddbgateway side.

And by the way, it would be nice to have some switch to be passed to the daemon so that it do not log all the IRC announcements but only the daemon events.

73 de Pedro

**Comment by moiei** [comment]
I have gathered more details... I have inserted logging traps in APRSCollector.cpp to see what was wrong and I got this:
```
M: 2018-07-03 22:04:45: Registered with dns.xreflector.net using callsign M0IEI
M: 2018-07-03 22:04:45: Loaded 30 DCS reflectors from dns.xreflector.net
M: 2018-07-03 22:04:47: CCS: M0IEI  C connected to server ccs704.xreflector.net
M: 2018-07-03 22:05:29: $GPRMC Valid
M: 2018-07-03 22:05:29: M0IEI>APDPRS,DSTAR*:!5224.40N\015.152EK
M: 2018-07-03 22:05:31: $GPRMC Valid
M: 2018-07-03 22:05:57: $$CRC Bad checksum
M: 2018-07-03 22:05:58: $$CRC Bad checksum
M: 2018-07-03 22:06:25: $$CRC Bad checksum
```
22:05:29 was using NMEA(DV-G) sending RMC, GGA, GLL and VTG sentences

Then I switched to D-PRS(DV-A) with Timestamp=off, Altitude=Off and Data Extension=off and I got all those CRC Bad Checksum.

So now we now know what it is not working OK with ID-51 plus 2. The positions are discarded by ircDDBGateway!

**Comment by dg0tm** [comment]
Hi all,

commit 8696548f3e6141d105a95fac775baed8337e82c2 removes the function
  void CAPRSWriter::setEnabled(bool enabled)
after that the timer m_idTimer gets never started.

I've no idea where is the right place the start this timer now.
